#pragma once
#include<cstdlib>
#include<dlfcn.h>
#include<fstream>
#include<functional>
#include<glad/glad.h>
#include<GLFW/glfw3.h>
#include<glm/glm.hpp>
#include<glm/gtc/type_ptr.hpp>
#include<glm/gtx/euler_angles.hpp>
#include<inttypes.h>
#include<iostream>
#include<KHR/khrplatform.h>
#include<stdint.h>
#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<unordered_map>
#include<vector>
